version: '3.9'

services:
  shell:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true

# Запускать так: docker-compose run --rm shell
# docker-compose.yaml для запуска этого образа вы найдете по ссылке https://github.com/staspykubsu/DockerUni2
